### ISSUE TITLE
友链申请

### ISSUE THREAD

**Issue by Fishskys** [1357310795/blog#2]
博客名：FIshsky的小窝
简介：生命不息，折腾不止
链接：https://fishsky.us.kg/
图片：https://fishsky.us.kg/upload/yanami64x64.png

**Comment by 1357310795** [comment]
不许不写关于页 😠

**Comment by Fishskys** [comment]
补上了补上了😫

**Comment by 1357310795** [comment]
FIsh的“I”确定是大写吗

**Comment by Fishskys** [comment]
是小写，没注意到打错了。Fishsky的小窝

**Comment by 1357310795** [comment]
push了，过10分钟应该就能看到

**Comment by Fishskys** [comment]
好的，我这边已经加上了
